import esbuild from 'esbuild'
import process from 'process'
import { rename } from 'node:fs/promises'
import { builtinModules } from 'node:module'
import esbuildSvelte from 'esbuild-svelte'
import { sveltePreprocess } from 'svelte-preprocess'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`

const prod = process.argv[2] === 'production'

/**
 * All plugin CSS (src/styles.css plus the Svelte component styles, emitted
 * next to main.js as main.css) ships as the static styles.css Obsidian loads
 * with the plugin, instead of being injected at runtime by the components.
 */
const stylesAsStaticCss = {
	name: 'styles-as-static-css',
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length === 0) await rename('main.css', 'styles.css')
		})
	},
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	target: 'es2018',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: 'main.js',
	minify: prod,
	plugins: [
		esbuildSvelte({
			compilerOptions: { css: 'external' },
			preprocess: sveltePreprocess(),
		}),
		stylesAsStaticCss,
	],
})

if (prod) {
	await context.rebuild()
	process.exit(0)
} else {
	await context.watch()
}
